import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 3000;

// Serve static files from the Vite build directory
// In a typical setup, 'dist' is the folder generated by 'npm run build'
app.use(express.static(path.join(__dirname, 'dist')));

// Handle SPA routing: Serve index.html for all non-file requests
app.get('*', (req, res) => {
    res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

app.listen(PORT, () => {
    console.log(`
  🚀 ISU Student Community Server is running!
  -------------------------------------------
  Local:   http://localhost:${PORT}
  Mode:    Production
  -------------------------------------------
  Organized & Managed by ISU.
    `);
});
